### ISSUE TITLE
ezcWorkflowExecutionException: There is no thread with id #0. 

### ISSUE THREAD

**Issue by chlab** [zetacomponents/Workflow#2]
I hope I'm posting this in the right place.

It seems that when the execution of a workflow passes through a SimpleMerge node for the third time, the following Exception occurs: There is no thread with id #0.
This issue may be related to [EZC-14190](https://jira.ez.no/browse/EZC-14190).

[Stracktrace](http://pastebin.com/a4kN3z0W) (relevant part)

Steps to reproduce:

``` php
require_once 'Base/src/base.php';

class DoSomething implements ezcWorkflowServiceObject
{
  public function execute(ezcWorkflowExecution $execution)
  {
    $loopCounter = $execution->getVariable('loopCounter');
    $execution->setVariable('loopCounter', ++$loopCounter);
  }

  public function __toString()
  {
    return 'doing something';
  }
}

class DoSomethingElse implements ezcWorkflowServiceObject
{
  public function execute(ezcWorkflowExecution $execution)
  {
    $loopCounter = $execution->getVariable('loopCounter');
    $execution->setVariable('loopCounter', ++$loopCounter);
  }

  public function __toString()
  {
    return 'doing something else';
  }
} 

// define workflow
$wf = new ezcWorkflow('loop_bug_test');

$setLoopCounter = new ezcWorkflowNodeVariableSet(array('loopCounter' => 1));
$setLoopCounter->addInNode($wf->startNode);

$doSomething = new ezcWorkflowNodeAction('DoSomething');
$doSomethingElse = new ezcWorkflowNodeAction('DoSomethingElse');

$loop = new ezcWorkflowNodeLoop;
$loop->addInNode($setLoopCounter);
$loop->addConditionalOutNode(
  new ezcWorkflowConditionVariable('loopCounter', new ezcWorkflowConditionIsLessThan(2)),
  $doSomething
  );
$loop->addConditionalOutNode(
  new ezcWorkflowConditionVariable('loopCounter', new ezcWorkflowConditionIsEqualOrGreaterThan(2)),
  $doSomethingElse
  );
$loop->addConditionalOutNode(
  new ezcWorkflowConditionVariable('loopCounter', new ezcWorkflowConditionIsGreaterThan(3)),
  $wf->endNode
  );

$merge = new ezcWorkflowNodeSimpleMerge;
$merge->addOutNode($loop);
$merge->addInNode($doSomething);
$merge->addInNode($doSomethingElse);
```

This code produces the following workflow:
![Loop Bug Workflow](http://imgur.com/mGIXg.png)

The execution should pass through the SimpleMerge node at the bottom three times but the above mentioned exception occurs.

On a sidenote: the reason the incrementation is done in the Service objects is that [ezcWorkflowNodeVariableIncrement](http://ezcomponents.org/docs/api/latest/Workflow/ezcWorkflowNodeVariableIncrement.html) does not seem to work as documented. It requires an operand even though the operand is hardcoded to "++" in [the code](http://ezcomponents.org/docs/api/latest/__filesource/fsource_Workflow---Workflow---1.4---src---nodes---variables---increment.php.html).

Background:
I wrote a workflow that orders something via an API. The API puts large orders into a queue to process asyncronously and returns a queueId and queueWait.
![Loop Bug Workflow](http://i.imgur.com/WmpCr.png)
In this case the workflow falls into a loop and checks the queue again after queueWait seconds have passed. If the queue still isn't ready and has to be checked a second time, the SimpleMerge node is passed a third time and the execution stops, again with the Exception above. The workflow works perfectly if the order is not queued or the queue only has to be checked once.

Environment:
I am developing with ezc Workflow v1.2 on Fedora 14. The workflows are stored with ezcWorkflowDatabaseDefinitionStorage.

Any help on this issue would be greatly appreciated after spending the whole day yesterday debugging and trying to find the problem or a workaround. Currently, my only workaround is to double the queue time and hope the queue won't have to be checked a second time.

**Comment by sebastianbergmann** [comment]
> Is Sebastian Bergmann no longer supporting this project?

I implemented this component as part of my Master Thesis back in 2006. After that, I fixed the occasional bug. I have not been involved in this project since 2010.

**Comment by chlab** [comment]
I vaguely remember having this problem but it‘s been 10 years and I don‘t remember how/if I solved it. I doubt the project I used this for exists anymore. Closing the issue :)
