### ISSUE TITLE
404 

### ISSUE THREAD

**Issue by BardiaAfshin** [zetacomponents/Workflow#9]
broken links in the documentation
http://is.tm.tue.nl/research/patterns/download/phd_bartek.pdf
and
http://sebastian-bergmann.de/publications/bergmann-WorkflowEngine-DiplomaThesis.pdf

in theoretical_background.txt

**Comment by derickr** [comment]
Hey @sebastianbergmann , what is the new URL for your thesis?

**Comment by sebastianbergmann** [comment]
It's now available again at https://sebastian-bergmann.de/publications/bergmann-WorkflowEngine-DiplomaThesis.pdf
